name: WORKFLOWS FILTERS

on:
    push:
        branches: 
            - main
            - '!feature/*'
        #branches-ignore: 
            #- feature/*
            #- test/** # va ignorer tout ce qui est test/a/b test/c/d
    workflow_dispatch:
    pull_request: 
        types: 
            - opened 
            - closed
        paths-ignore: 
            - README.md
        branches: 
            - main

env: 
    CONTAINER_REGISTRY: docker.io
    IAMGE_NAME: github-actions-nginx
    DOCKER_USERNAME: siddharth1
    DOCKER_PASSWORD: s3cUrePassw0rd

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
         - name: Docker Build 
           run:  echo docker build -t ${{env.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/$IAMGE_NAME:latest

         - name: Docker login
           run:  echo docker login --username=${{vars.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}}
        
         - name: Docker Publih
           run:  echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IAMGE_NAME:latest

  